services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volume:
      - ./server:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
